#!/bin/bash

if [ "$#" -lt 2 ]; then
    >&2 echo "usage: $(basename "$0") <x509up> <prog> [args...]"
    exit 1
fi

set -euo pipefail

export X509_USER_PROXY=/tmp/x509up_u$UID
cp "$1" "${X509_USER_PROXY}"
chmod 600 "${X509_USER_PROXY}"

voms-proxy-info

# xrootd-dependent tools expect HOME to point to a real AFS home.
export HOME="/afs/cern.ch/user/${USER:0:1}/${USER}"

PROG="$(readlink -f "$2")"
shift 2
exec "${PROG}" "$@"
